# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Amathon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'Cosmos', '~> 16.0'

  # Pods for Amathon

end
post_install do |installer|
installer.pods_project.build_configurations.each do |config|
config.build_settings.delete('CODE_SIGNING_ALLOWED')
config.build_settings.delete('CODE_SIGNING_REQUIRED')
end
end