# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Amathon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'

  # Pods for Amathon

end
